// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWLYdIN_bb84l0Aaxhhna-QsxcgQ8CyaQ',
    appId: '1:53633026618:web:155681fce6197d2ca54303',
    messagingSenderId: '53633026618',
    projectId: 'esshp-e9a3e',
    authDomain: 'esshp-e9a3e.firebaseapp.com',
    storageBucket: 'esshp-e9a3e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtApvnjn4AUyjglgKdLDveIr2C3FdmXL0',
    appId: '1:53633026618:android:db782ecc5613bb20a54303',
    messagingSenderId: '53633026618',
    projectId: 'esshp-e9a3e',
    storageBucket: 'esshp-e9a3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfm3M6MiZ6nzQr6Xp7jRfnP7DB_fpcVCw',
    appId: '1:53633026618:ios:2e3b01891406823aa54303',
    messagingSenderId: '53633026618',
    projectId: 'esshp-e9a3e',
    storageBucket: 'esshp-e9a3e.firebasestorage.app',
    iosBundleId: 'com.lebetak.usersapp',
  );

}